@baseURL = http://localhost:9200

### GET All existed index

GET {{baseURL}}/_aliases

@index = daily_demo_tweet

### Create new index

PUT {{baseURL}}/{{index}}

### Get info of the index

GET  {{baseURL}}/{{index}}

### Create new document

PUT {{baseURL}}/{{index}}/_doc/1
Content-Type: application/json

{
    "user": "testAccount",
    "content": "This is a test doc"
}

### Get new specific document

GET  {{baseURL}}/{{index}}/_doc/1

### Update a record

POST {{baseURL}}/{{index}}/_doc/1
Content-Type: application/json

{
    "user": "testAccount",
    "content": "Change the content"
}

### Delete a record
DELETE {{baseURL}}/{{index}}/_doc/1
